steps:

- id: "Rodando docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.28.2'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']

- id: "Chown in /var/www"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-u','root','-t','micro-videos-app','chown','-R','www-data:www-data','/var/www']

- id: "Rodando o composer"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'micro-videos-app', 'composer', 'install']

- id: "Copiando .env"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'micro-videos-app', 'cp', '.env.example', '.env']

- id: "Rodando key:generate"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'key:generate']

- id: "Rodando migrations"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'migrate']

- id: "Rodando testes com phpunit"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/vendon/bin/phpunit', '-c', '/var/www/phpunit.xml']